### ISSUE TITLE
番茄钟

### ISSUE THREAD

**Issue by zpystudy** [JuckZ/awesome-brain-manager#11]
### Describe the bug

今天最新发布的1.6.0版本，任务暂停时番茄钟没有暂停

### Expected Behavior

任务暂停时番茄钟应该也停止计时

### Steps to reproduce

![image](https://user-images.githubusercontent.com/67833719/223437354-083d52da-6c23-4be4-8211-402b0be3fca5.png)

### Operating system

Windows

**Comment by JuckZ** [comment]
抱歉，忘记提交修复代码
