### ISSUE TITLE
[Bug]: failed to load plugin 

### ISSUE THREAD

**Issue by limrli** [JuckZ/awesome-brain-manager#14]
### Describe the bug

![image](https://user-images.githubusercontent.com/68333993/223666674-97767b07-bc14-4e64-ad99-71442ebc8b35.png)
![image](https://user-images.githubusercontent.com/68333993/223666595-a57c753d-7337-485e-9407-359e1114a235.png)

### Steps to reproduce

无法使用，点击打开按钮，自动关闭。显示如上报错信息

### Operating system

Windows

**Comment by JuckZ** [comment]
能使用Ctrl+Shift+I打开控制台把更多错误信息提供给我吗

**Comment by JuckZ** [comment]
这个问题和 #8 应该属于同一个问题，可以在 #8 中进行讨论，关闭此issue

**Comment by JuckZ** [comment]
#15 已经解决该bug
