### ISSUE TITLE
[Bug]: 2个bug

### ISSUE THREAD

**Issue by iczrac** [JuckZ/awesome-brain-manager#18]
### Describe the bug

bug1：开启插件后，重启，库的目录文件都不见了，见下图

我用的cuman的blue topaz例库

![Snipaste_2023-03-24_15-43-52](https://user-images.githubusercontent.com/73928031/227457510-2929481f-034e-4d19-b730-2d0061483c31.png)

关闭插件后，重启恢复正常

bug2：在Obsidian右键会自动跳到下一行，规划番茄钟时不能记录准确的名称，如下图
这个问题我新开库也是这样跳转，不知道怎么修正，请教一下如何做好教程视频的效果
![Snipaste_2023-03-24_15-15-28](https://user-images.githubusercontent.com/73928031/227459920-6ccfbdc9-23e2-43bf-8f39-7cb4f023a40a.png)

谢谢

### Steps to reproduce

如上述

### Operating system

macOS

**Comment by iczrac** [comment]
发现bug1是homepage插件造成的，关闭下面的按键就可以恢复

![image](https://user-images.githubusercontent.com/73928031/227470533-9646d245-2d81-48a0-8021-01511c786bb0.png)

**Comment by JuckZ** [comment]
感谢反馈，但可能需要我有时间的时候才能修复，如果你能提供更详细的报错信息或许能帮助我尽快处理问题

**Comment by JuckZ** [comment]
bug2我这里也不能复现，暂时关闭改issue
