### ISSUE TITLE
[Bug]: <阅读与预览模式下的表情显示不一致>

### ISSUE THREAD

**Issue by TheGodOfKing** [JuckZ/awesome-brain-manager#19]
### Describe the bug

![5SJEKZW6FV93VG{})MRL%A7](https://user-images.githubusercontent.com/32014745/227790384-97ff464a-11f6-478d-80f0-e77cc70dd31b.gif)

阅读与预览模式下的表情显示不一致，关闭插件后就显示一致了，通过观察源码发现，表情在阅读模式下竟然变成了网络图片！！！！！！

![bug2](https://user-images.githubusercontent.com/32014745/227792717-4b24c545-a486-457d-9f83-ac594b3d0229.gif)

![image](https://user-images.githubusercontent.com/32014745/227790109-bd75e25f-7236-44fe-9e89-fc1f23ea5a1f.png)

**希望能修复!!!!!!**

![%6Y{9_$49JXA9G_80C08892](https://user-images.githubusercontent.com/32014745/227790337-6c2696ee-08ef-41ed-baf9-2b3d36e1f06f.gif)

### Expected Behavior

表情在阅读和预览的模式应该显示一致

### Steps to reproduce

打开插件->添加表情->切换阅读与预览模式

### Operating system

Windows

**Comment by JuckZ** [comment]
感谢反馈，最近比较忙，有时间会处理的
