### ISSUE TITLE
[Feature]: Pomodoro in status bar

### ISSUE THREAD

**Issue by AndyLiu9** [JuckZ/awesome-brain-manager#20]
### Goal or desired outcome of this feature

Shows the title & timer for the ongoing pomodoro

### Describe the feature

![image](https://user-images.githubusercontent.com/88693956/228178314-02479a04-c163-4338-9e25-9e6db37411bc.png)
like this one

**Comment by JuckZ** [comment]
I'll deal with it in a few days， thanks for the feedback
