### ISSUE TITLE
[Bug]: 请问一下，为什么我开启插件，我本身的外观字体会发生变化，另外可以做一版中文的吗？

### ISSUE THREAD

**Issue by YIRU69** [JuckZ/awesome-brain-manager#3]
### Describe the bug

为什么我开启插件，我本身的外观字体会发生变化，另外可以做一版中文的吗？

我没有开启插件是这样的
![image](https://user-images.githubusercontent.com/48148292/218250683-c6b9e690-30f6-45c8-bdf6-6fd3301a9243.png)
开启后是这样
![image](https://user-images.githubusercontent.com/48148292/218250702-ad2b17f5-09b3-494c-9952-ea3c2e476ccc.png)

另外能增加文字使用说明吗？功能有点多，对我来说，真正需要的是提醒和番茄钟

### Steps to reproduce

如图

### Operating system

Windows

**Comment by JuckZ** [comment]
> ### Describe the bug
> 
> 为什么我开启插件，我本身的外观字体会发生变化，另外可以做一版中文的吗？
> 
> 我没有开启插件是这样的 ![image](https://user-images.githubusercontent.com/48148292/218250683-c6b9e690-30f6-45c8-bdf6-6fd3301a9243.png) 开启后是这样 ![image](https://user-images.githubusercontent.com/48148292/218250702-ad2b17f5-09b3-494c-9952-ea3c2e476ccc.png)
> 
> 另外能增加文字使用说明吗？功能有点多，对我来说，真正需要的是提醒和番茄钟
> ### Expected Behavior
> 
> _No response_
> ### Steps to reproduce
> 
> 如图
> ### Operating system
> 
> Windows

感谢你的建议，正在处理中 @YIRU69

**Comment by JuckZ** [comment]
已经发布了新版，处理了你提及的问题: 1.[国际化支持](https://github.com/JuckZ/awesome-brain-manager/commit/b9177f09c2a3a614aafade6ab44f55cc215010b9) 2.[样式冲突问题](https://github.com/JuckZ/awesome-brain-manager/commit/a5c834ae55cd7b84e6a94ec531f3c50623ef6191) ，随后将关闭该issue @YIRU69

**Comment by JuckZ** [comment]
> 

1.3版本

**Comment by YIRU69** [comment]
收到，谢谢
