### ISSUE TITLE
[Feature]: 预设番茄钟任务

### ISSUE THREAD

**Issue by daoif** [JuckZ/awesome-brain-manager#37]
### Goal or desired outcome of this feature

我的使用习惯是,使用番茄钟时并不写详细要做的事情,而是一个状态,是工作,还是休息?让自己有一个时间预期.

### Describe the feature

放在时间轴上面,点一下添加任务(并开始)
而任务的预设可以设置不同的时间.

### Screenshots, mockups, or videos
![image](https://github.com/JuckZ/awesome-brain-manager/assets/46199660/6b889ff1-ac0e-4a4a-99ec-487752991494)
_No response_

**Comment by daoif** [comment]
本来打算fork一份自己增加这个功能的,但对obsidian的插件开发实在是不熟练,搞了一下午没弄好.
最后弄了个网页实现了定时器的功能.

**Comment by aramalipoor** [comment]
Hi @daoif can you send me an email (`aram.alipoor@gmail.com`), I want to talk to you about https://www.npmjs.com/package/erpc package :)
