### ISSUE TITLE
[Question]: The calendar shown in the screenshot 

### ISSUE THREAD

**Issue by Hexara7777** [JuckZ/awesome-brain-manager#39]
### Goal or desired outcome of this feature

Hi there, I would like to know if the Calendar show in the screenshot in Readme.md is the one in the roadmap or you just use a currently available plugin? 

### Describe the feature

.

**Comment by JuckZ** [comment]
I don't quite understand what you mean. Can you describe it more clearly

**Comment by Hexara7777** [comment]
> I don't quite understand what you mean. Can you describe it more clearly

Hi there @JuckZ I meant this one here
![番茄钟示例](https://github.com/JuckZ/awesome-brain-manager/assets/130001839/c97685dc-3ffb-4078-aa94-b39f6e3491d1)
Where to get this calendar and dashboard?
