### ISSUE TITLE
插件在obsidian中的加载速度似乎有点慢

### ISSUE THREAD

**Issue by Wolfdebug** [JuckZ/awesome-brain-manager#4]
### Goal or desired outcome of this feature

启动时候的加载速度知道能不能优化下，也可能是插件比较大吧。抱歉我不是专业的，只是提出我的疑惑

### Describe the feature

软件启动速度后，插件加载速度在100ms内

### Screenshots, mockups, or videos

![image](https://user-images.githubusercontent.com/26107190/222035130-1beac381-8c29-4137-867b-b0949c7ee3cd.png)

**Comment by JuckZ** [comment]
在持续优化中，感谢反馈 @Wolfdebug

**Comment by JuckZ** [comment]
现在基本能在200ms左右启动完毕，会持续优化，因为插件功能非常多，所以100ms只能说是目标，但是没办法硬性去达到
![图片](https://user-images.githubusercontent.com/35656100/223412841-f2bd8afc-43e7-42d3-af9e-dd19abfe80d8.png)
