### ISSUE TITLE
只能在OB里面提醒，外面工作的时候不知道。[Feature]: <TITLE>

### ISSUE THREAD

**Issue by BIGPER** [JuckZ/awesome-brain-manager#5]
### Goal or desired outcome of this feature

开始了一个番茄任务，番茄任务已经开始计时，番茄任务完成时没有声音或者不能弹出整个OB，在外面专注的时候不知道已经到了这个时间，不得已要切换看看还剩下多少时间，但是这样就违背了专注的意义了。希望能够增加声音提醒或者OB弹窗提醒能够把整个OB弹出来，而不是在里面。

### Describe the feature

弹出整个OB作为提醒，或声音提醒。

**Comment by JuckZ** [comment]
已经支持该功能，即将发布新版，感谢反馈 @BIGPER

**Comment by JuckZ** [comment]
[1.6版本](https://github.com/JuckZ/awesome-brain-manager/releases/tag/1.6.0)已经支持系统原生提醒、声音提醒以及ntfy全终端跨平台的提醒方案
