### ISSUE TITLE
[Bug]: <插件无法加载>

### ISSUE THREAD

**Issue by BIGPER** [JuckZ/awesome-brain-manager#8]
### Describe the bug

点击安装插件，显示不能载入插件。
![image](https://user-images.githubusercontent.com/93172633/223294617-5edbe975-3f45-479a-852e-b5a2341107e4.png)

### Steps to reproduce

昨天突然上传了2个版本，1.4和1.5 我下载的1.5显示版本号还是1.4、

### Operating system

Windows

**Comment by JuckZ** [comment]
为了更好帮助到你，麻烦提供更多报错信息 @BIGPER

**Comment by JuckZ** [comment]
#15  已经解决该bug
